bin('/bin/arch').
bin('/bin/ash').
bin('/bin/base64').
bin('/bin/bbconfig').
bin('/bin/busybox').
bin('/bin/cat').
bin('/bin/chattr').
bin('/bin/chgrp').
bin('/bin/chmod').
bin('/bin/chown').
bin('/bin/cp').
bin('/bin/date').
bin('/bin/dd').
bin('/bin/df').
bin('/bin/dmesg').
bin('/bin/dnsdomainname').
bin('/bin/dumpkmap').
bin('/bin/echo').
bin('/bin/egrep').
bin('/bin/false').
bin('/bin/fatattr').
bin('/bin/fdflush').
bin('/bin/fgrep').
bin('/bin/fsync').
bin('/bin/getopt').
bin('/bin/grep').
bin('/bin/gunzip').
bin('/bin/gzip').
bin('/bin/hostname').
bin('/bin/ionice').
bin('/bin/iostat').
bin('/bin/ipcalc').
bin('/bin/kbd_mode').
bin('/bin/kill').
bin('/bin/link').
bin('/bin/linux32').
bin('/bin/linux64').
bin('/bin/ln').
bin('/bin/login').
bin('/bin/ls').
bin('/bin/lsattr').
bin('/bin/lzop').
bin('/bin/makemime').
bin('/bin/mkdir').
bin('/bin/mknod').
bin('/bin/mktemp').
bin('/bin/more').
bin('/bin/mount').
bin('/bin/mountpoint').
bin('/bin/mpstat').
bin('/bin/mv').
bin('/bin/netstat').
bin('/bin/nice').
bin('/bin/pidof').
bin('/bin/ping').
bin('/bin/ping6').
bin('/bin/pipe_progress').
bin('/bin/printenv').
bin('/bin/ps').
bin('/bin/pwd').
bin('/bin/reformime').
bin('/bin/rev').
bin('/bin/rm').
bin('/bin/rmdir').
bin('/bin/run-parts').
bin('/bin/sed').
bin('/bin/setpriv').
bin('/bin/setserial').
bin('/bin/sh').
bin('/bin/sleep').
bin('/bin/stat').
bin('/bin/stty').
bin('/bin/su').
bin('/bin/sync').
bin('/bin/tar').
bin('/bin/touch').
bin('/bin/true').
bin('/bin/umount').
bin('/bin/uname').
bin('/bin/usleep').
bin('/bin/watch').
bin('/bin/zcat').
bin('/sbin/acpid').
bin('/sbin/adjtimex').
bin('/sbin/apk').
bin('/sbin/arp').
bin('/sbin/blkdiscard').
bin('/sbin/blkid').
bin('/sbin/blockdev').
bin('/sbin/depmod').
bin('/sbin/fbsplash').
bin('/sbin/fdisk').
bin('/sbin/findfs').
bin('/sbin/fsck').
bin('/sbin/fstrim').
bin('/sbin/getty').
bin('/sbin/halt').
bin('/sbin/hwclock').
bin('/sbin/ifconfig').
bin('/sbin/ifdown').
bin('/sbin/ifenslave').
bin('/sbin/ifup').
bin('/sbin/init').
bin('/sbin/inotifyd').
bin('/sbin/insmod').
bin('/sbin/ip').
bin('/sbin/ipaddr').
bin('/sbin/iplink').
bin('/sbin/ipneigh').
bin('/sbin/iproute').
bin('/sbin/iprule').
bin('/sbin/iptunnel').
bin('/sbin/klogd').
bin('/sbin/ldconfig').
bin('/sbin/loadkmap').
bin('/sbin/logread').
bin('/sbin/losetup').
bin('/sbin/lsmod').
bin('/sbin/mdev').
bin('/sbin/mkdosfs').
bin('/sbin/mkfs.vfat').
bin('/sbin/mkswap').
bin('/sbin/modinfo').
bin('/sbin/modprobe').
bin('/sbin/nameif').
bin('/sbin/nologin').
bin('/sbin/pivot_root').
bin('/sbin/poweroff').
bin('/sbin/raidautorun').
bin('/sbin/reboot').
bin('/sbin/rmmod').
bin('/sbin/route').
bin('/sbin/setconsole').
bin('/sbin/slattach').
bin('/sbin/swapoff').
bin('/sbin/swapon').
bin('/sbin/switch_root').
bin('/sbin/sysctl').
bin('/sbin/syslogd').
bin('/sbin/tunctl').
bin('/sbin/udhcpc').
bin('/sbin/vconfig').
bin('/sbin/watchdog').
bin('/sbin/zcip').
bin('/usr/bin/[').
bin('/usr/bin/[[').
bin('/usr/bin/acyclic').
bin('/usr/bin/aserver').
bin('/usr/bin/awk').
bin('/usr/bin/basename').
bin('/usr/bin/bc').
bin('/usr/bin/bcomps').
bin('/usr/bin/beep').
bin('/usr/bin/bomtool').
bin('/usr/bin/broadwayd').
bin('/usr/bin/bunzip2').
bin('/usr/bin/bwrap').
bin('/usr/bin/bzcat').
bin('/usr/bin/bzip2').
bin('/usr/bin/cal').
bin('/usr/bin/ccomps').
bin('/usr/bin/cflow').
bin('/usr/bin/chvt').
bin('/usr/bin/circo').
bin('/usr/bin/cksum').
bin('/usr/bin/clear').
bin('/usr/bin/cluster').
bin('/usr/bin/cmp').
bin('/usr/bin/comm').
bin('/usr/bin/cpio').
bin('/usr/bin/crontab').
bin('/usr/bin/cryptpw').
bin('/usr/bin/cut').
bin('/usr/bin/cxpm').
bin('/usr/bin/dc').
bin('/usr/bin/deallocvt').
bin('/usr/bin/diff').
bin('/usr/bin/diffimg').
bin('/usr/bin/dijkstra').
bin('/usr/bin/dirname').
bin('/usr/bin/dos2unix').
bin('/usr/bin/dot').
bin('/usr/bin/dot2gxl').
bin('/usr/bin/dot_builtins').
bin('/usr/bin/dot_sandbox').
bin('/usr/bin/doxygen').
bin('/usr/bin/du').
bin('/usr/bin/econftool').
bin('/usr/bin/edgepaint').
bin('/usr/bin/eject').
bin('/usr/bin/env').
bin('/usr/bin/expand').
bin('/usr/bin/expr').
bin('/usr/bin/factor').
bin('/usr/bin/fallocate').
bin('/usr/bin/fc-cache').
bin('/usr/bin/fc-cat').
bin('/usr/bin/fc-conflist').
bin('/usr/bin/fc-list').
bin('/usr/bin/fc-match').
bin('/usr/bin/fc-pattern').
bin('/usr/bin/fc-query').
bin('/usr/bin/fc-scan').
bin('/usr/bin/fc-validate').
bin('/usr/bin/fdp').
bin('/usr/bin/fftw-wisdom').
bin('/usr/bin/fftw-wisdom-to-conf').
bin('/usr/bin/fftwf-wisdom').
bin('/usr/bin/fftwl-wisdom').
bin('/usr/bin/find').
bin('/usr/bin/findssl.sh').
bin('/usr/bin/firefox').
bin('/usr/bin/flock').
bin('/usr/bin/fold').
bin('/usr/bin/free').
bin('/usr/bin/freerdp-proxy3').
bin('/usr/bin/freerdp-shadow-cli3').
bin('/usr/bin/fribidi').
bin('/usr/bin/fuser').
bin('/usr/bin/gapplication').
bin('/usr/bin/gc').
bin('/usr/bin/gdbus').
bin('/usr/bin/gdk-pixbuf-csource').
bin('/usr/bin/gdk-pixbuf-pixdata').
bin('/usr/bin/gdk-pixbuf-query-loaders').
bin('/usr/bin/getconf').
bin('/usr/bin/getent').
bin('/usr/bin/gi-compile-repository').
bin('/usr/bin/gi-decompile-typelib').
bin('/usr/bin/gi-inspect-typelib').
bin('/usr/bin/gio').
bin('/usr/bin/gio-querymodules').
bin('/usr/bin/glib-compile-schemas').
bin('/usr/bin/gml2gv').
bin('/usr/bin/graphml2gv').
bin('/usr/bin/groups').
bin('/usr/bin/gsettings').
bin('/usr/bin/gtk-launch').
bin('/usr/bin/gtk-query-immodules-3.0').
bin('/usr/bin/gv2gml').
bin('/usr/bin/gv2gxl').
bin('/usr/bin/gvcolor').
bin('/usr/bin/gvgen').
bin('/usr/bin/gvmap').
bin('/usr/bin/gvmap.sh').
bin('/usr/bin/gvpack').
bin('/usr/bin/gvpr').
bin('/usr/bin/gxl2dot').
bin('/usr/bin/gxl2gv').
bin('/usr/bin/hd').
bin('/usr/bin/head').
bin('/usr/bin/hexdump').
bin('/usr/bin/hostid').
bin('/usr/bin/iconv').
bin('/usr/bin/id').
bin('/usr/bin/install').
bin('/usr/bin/ipcrm').
bin('/usr/bin/ipcs').
bin('/usr/bin/killall').
bin('/usr/bin/last').
bin('/usr/bin/ldd').
bin('/usr/bin/less').
bin('/usr/bin/logger').
bin('/usr/bin/lsof').
bin('/usr/bin/lsusb').
bin('/usr/bin/lz4').
bin('/usr/bin/lz4c').
bin('/usr/bin/lz4cat').
bin('/usr/bin/lzcat').
bin('/usr/bin/lzma').
bin('/usr/bin/lzopcat').
bin('/usr/bin/md5sum').
bin('/usr/bin/mesg').
bin('/usr/bin/microcom').
bin('/usr/bin/mkfifo').
bin('/usr/bin/mkfontdir').
bin('/usr/bin/mkfontscale').
bin('/usr/bin/mkpasswd').
bin('/usr/bin/mm2gv').
bin('/usr/bin/nc').
bin('/usr/bin/neato').
bin('/usr/bin/nl').
bin('/usr/bin/nmeter').
bin('/usr/bin/nohup').
bin('/usr/bin/nop').
bin('/usr/bin/nproc').
bin('/usr/bin/nsenter').
bin('/usr/bin/nslookup').
bin('/usr/bin/od').
bin('/usr/bin/openssl').
bin('/usr/bin/openvt').
bin('/usr/bin/osage').
bin('/usr/bin/p11-kit').
bin('/usr/bin/passwd').
bin('/usr/bin/paste').
bin('/usr/bin/patchwork').
bin('/usr/bin/pgrep').
bin('/usr/bin/pkg-config').
bin('/usr/bin/pkgconf').
bin('/usr/bin/pkill').
bin('/usr/bin/pmap').
bin('/usr/bin/printf').
bin('/usr/bin/prune').
bin('/usr/bin/pscan').
bin('/usr/bin/pstree').
bin('/usr/bin/pwdx').
bin('/usr/bin/readlink').
bin('/usr/bin/realpath').
bin('/usr/bin/renice').
bin('/usr/bin/reset').
bin('/usr/bin/resize').
bin('/usr/bin/scanelf').
bin('/usr/bin/sccmap').
bin('/usr/bin/scmp_sys_resolver').
bin('/usr/bin/scp').
bin('/usr/bin/sdl-freerdp3').
bin('/usr/bin/seq').
bin('/usr/bin/setkeycodes').
bin('/usr/bin/setsid').
bin('/usr/bin/sfdp').
bin('/usr/bin/sfreerdp-server3').
bin('/usr/bin/sfreerdp3').
bin('/usr/bin/sftp').
bin('/usr/bin/sha1sum').
bin('/usr/bin/sha256sum').
bin('/usr/bin/sha3sum').
bin('/usr/bin/sha512sum').
bin('/usr/bin/showkey').
bin('/usr/bin/shred').
bin('/usr/bin/shuf').
bin('/usr/bin/sort').
bin('/usr/bin/spirv-as').
bin('/usr/bin/spirv-cfg').
bin('/usr/bin/spirv-diff').
bin('/usr/bin/spirv-dis').
bin('/usr/bin/spirv-lesspipe.sh').
bin('/usr/bin/spirv-link').
bin('/usr/bin/spirv-lint').
bin('/usr/bin/spirv-objdump').
bin('/usr/bin/spirv-opt').
bin('/usr/bin/spirv-reduce').
bin('/usr/bin/spirv-val').
bin('/usr/bin/split').
bin('/usr/bin/ssh').
bin('/usr/bin/ssh-add').
bin('/usr/bin/ssh-agent').
bin('/usr/bin/ssh-copy-id').
bin('/usr/bin/ssh-keygen').
bin('/usr/bin/ssh-keyscan').
bin('/usr/bin/ssh-pkcs11-helper').
bin('/usr/bin/ssl_client').
bin('/usr/bin/strings').
bin('/usr/bin/sum').
bin('/usr/bin/sxpm').
bin('/usr/bin/tac').
bin('/usr/bin/tail').
bin('/usr/bin/tee').
bin('/usr/bin/test').
bin('/usr/bin/time').
bin('/usr/bin/timeout').
bin('/usr/bin/top').
bin('/usr/bin/tr').
bin('/usr/bin/traceroute').
bin('/usr/bin/traceroute6').
bin('/usr/bin/tred').
bin('/usr/bin/tree').
bin('/usr/bin/truncate').
bin('/usr/bin/tty').
bin('/usr/bin/ttysize').
bin('/usr/bin/twopi').
bin('/usr/bin/udhcpc6').
bin('/usr/bin/unexpand').
bin('/usr/bin/unflatten').
bin('/usr/bin/uniq').
bin('/usr/bin/unix2dos').
bin('/usr/bin/unlink').
bin('/usr/bin/unlz4').
bin('/usr/bin/unlzma').
bin('/usr/bin/unlzop').
bin('/usr/bin/unshare').
bin('/usr/bin/unxz').
bin('/usr/bin/unzip').
bin('/usr/bin/update-mime-database').
bin('/usr/bin/uptime').
bin('/usr/bin/uudecode').
bin('/usr/bin/uuencode').
bin('/usr/bin/vi').
bin('/usr/bin/vimdot').
bin('/usr/bin/vlock').
bin('/usr/bin/volname').
bin('/usr/bin/wc').
bin('/usr/bin/wget').
bin('/usr/bin/which').
bin('/usr/bin/who').
bin('/usr/bin/whoami').
bin('/usr/bin/whois').
bin('/usr/bin/winpr-hash3').
bin('/usr/bin/winpr-makecert3').
bin('/usr/bin/wlfreerdp3').
bin('/usr/bin/xargs').
bin('/usr/bin/xfreerdp3').
bin('/usr/bin/xxd').
bin('/usr/bin/xzcat').
bin('/usr/bin/yes').
bin('/usr/bin/yuvconvert').
bin('/usr/sbin/add-shell').
bin('/usr/sbin/addgroup').
bin('/usr/sbin/adduser').
bin('/usr/sbin/arping').
bin('/usr/sbin/brctl').
bin('/usr/sbin/chpasswd').
bin('/usr/sbin/chroot').
bin('/usr/sbin/crond').
bin('/usr/sbin/delgroup').
bin('/usr/sbin/deluser').
bin('/usr/sbin/ether-wake').
bin('/usr/sbin/fbset').
bin('/usr/sbin/killall5').
bin('/usr/sbin/loadfont').
bin('/usr/sbin/nanddump').
bin('/usr/sbin/nandwrite').
bin('/usr/sbin/nbd-client').
bin('/usr/sbin/ntpd').
bin('/usr/sbin/partprobe').
bin('/usr/sbin/rdate').
bin('/usr/sbin/rdev').
bin('/usr/sbin/readahead').
bin('/usr/sbin/remove-shell').
bin('/usr/sbin/rfkill').
bin('/usr/sbin/sendmail').
bin('/usr/sbin/setfont').
bin('/usr/sbin/setlogcons').
bin('/usr/sbin/sshd').
lib('/lib/ld-musl-aarch64.so.1').
lib('/lib/libc.musl-aarch64.so.1').
lib('/usr/lib/cairo/libcairo-fdr.so').
lib('/usr/lib/engines-3/afalg.so').
lib('/usr/lib/engines-3/capi.so').
lib('/usr/lib/engines-3/loader_attic.so').
lib('/usr/lib/engines-3/padlock.so').
lib('/usr/lib/firefox/gmp-clearkey/0.1/libclearkey.so').
lib('/usr/lib/firefox/libgkcodecs.so').
lib('/usr/lib/firefox/liblgpllibs.so').
lib('/usr/lib/firefox/libmozavcodec.so').
lib('/usr/lib/firefox/libmozavutil.so').
lib('/usr/lib/firefox/libmozgtk.so').
lib('/usr/lib/firefox/libmozinference.so').
lib('/usr/lib/firefox/libmozsandbox.so').
lib('/usr/lib/firefox/libmozsqlite3.so').
lib('/usr/lib/firefox/libmozwayland.so').
lib('/usr/lib/firefox/libxul.so').
lib('/usr/lib/freerdp3/proxy/libproxy-bitmap-filter-plugin.so').
lib('/usr/lib/freerdp3/proxy/libproxy-demo-plugin.so').
lib('/usr/lib/freerdp3/proxy/libproxy-dyn-channel-dump-plugin.so').
lib('/usr/lib/gbm/dri_gbm.so').
lib('/usr/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-xpm.so').
lib('/usr/lib/graphviz/libgvplugin_core.so').
lib('/usr/lib/graphviz/libgvplugin_core.so.6').
lib('/usr/lib/graphviz/libgvplugin_core.so.6.0.0').
lib('/usr/lib/graphviz/libgvplugin_dot_layout.so').
lib('/usr/lib/graphviz/libgvplugin_dot_layout.so.6').
lib('/usr/lib/graphviz/libgvplugin_dot_layout.so.6.0.0').
lib('/usr/lib/graphviz/libgvplugin_gd.so').
lib('/usr/lib/graphviz/libgvplugin_gd.so.6').
lib('/usr/lib/graphviz/libgvplugin_gd.so.6.0.0').
lib('/usr/lib/graphviz/libgvplugin_kitty.so').
lib('/usr/lib/graphviz/libgvplugin_kitty.so.6').
lib('/usr/lib/graphviz/libgvplugin_kitty.so.6.0.0').
lib('/usr/lib/graphviz/libgvplugin_neato_layout.so').
lib('/usr/lib/graphviz/libgvplugin_neato_layout.so.6').
lib('/usr/lib/graphviz/libgvplugin_neato_layout.so.6.0.0').
lib('/usr/lib/graphviz/libgvplugin_pango.so').
lib('/usr/lib/graphviz/libgvplugin_pango.so.6').
lib('/usr/lib/graphviz/libgvplugin_pango.so.6.0.0').
lib('/usr/lib/graphviz/libgvplugin_vt.so').
lib('/usr/lib/graphviz/libgvplugin_vt.so.6').
lib('/usr/lib/graphviz/libgvplugin_vt.so.6.0.0').
lib('/usr/lib/graphviz/libgvplugin_webp.so').
lib('/usr/lib/graphviz/libgvplugin_webp.so.6').
lib('/usr/lib/graphviz/libgvplugin_webp.so.6.0.0').
lib('/usr/lib/graphviz/libgvplugin_xlib.so').
lib('/usr/lib/graphviz/libgvplugin_xlib.so.6').
lib('/usr/lib/graphviz/libgvplugin_xlib.so.6.0.0').
lib('/usr/lib/gtk-2.0/modules/libatk-bridge.so').
lib('/usr/lib/gtk-3.0/3.0.0/immodules/im-am-et.so').
lib('/usr/lib/gtk-3.0/3.0.0/immodules/im-broadway.so').
lib('/usr/lib/gtk-3.0/3.0.0/immodules/im-cedilla.so').
lib('/usr/lib/gtk-3.0/3.0.0/immodules/im-cyrillic-translit.so').
lib('/usr/lib/gtk-3.0/3.0.0/immodules/im-inuktitut.so').
lib('/usr/lib/gtk-3.0/3.0.0/immodules/im-ipa.so').
lib('/usr/lib/gtk-3.0/3.0.0/immodules/im-multipress.so').
lib('/usr/lib/gtk-3.0/3.0.0/immodules/im-thai.so').
lib('/usr/lib/gtk-3.0/3.0.0/immodules/im-ti-er.so').
lib('/usr/lib/gtk-3.0/3.0.0/immodules/im-ti-et.so').
lib('/usr/lib/gtk-3.0/3.0.0/immodules/im-viqr.so').
lib('/usr/lib/gtk-3.0/3.0.0/immodules/im-wayland.so').
lib('/usr/lib/gtk-3.0/3.0.0/immodules/im-xim.so').
lib('/usr/lib/gtk-3.0/3.0.0/printbackends/libprintbackend-cups.so').
lib('/usr/lib/gtk-3.0/3.0.0/printbackends/libprintbackend-file.so').
lib('/usr/lib/gtk-3.0/3.0.0/printbackends/libprintbackend-lpr.so').
lib('/usr/lib/krb5/plugins/kdb/db2.so').
lib('/usr/lib/krb5/plugins/preauth/otp.so').
lib('/usr/lib/krb5/plugins/preauth/spake.so').
lib('/usr/lib/krb5/plugins/preauth/test.so').
lib('/usr/lib/krb5/plugins/tls/k5tls.so').
lib('/usr/lib/libEGL.so.1').
lib('/usr/lib/libEGL.so.1.0.0').
lib('/usr/lib/libGL.so.1').
lib('/usr/lib/libGL.so.1.2.0').
lib('/usr/lib/libGLESv1_CM.so.1').
lib('/usr/lib/libGLESv1_CM.so.1.1.0').
lib('/usr/lib/libGLESv2.so.2').
lib('/usr/lib/libGLESv2.so.2.0.0').
lib('/usr/lib/libICE.so.6').
lib('/usr/lib/libICE.so.6.3.0').
lib('/usr/lib/libLLVM-22.so').
lib('/usr/lib/libLLVM.so.22.1').
lib('/usr/lib/libSDL3.so.0').
lib('/usr/lib/libSDL3.so.0.4.10').
lib('/usr/lib/libSDL3_ttf.so.0').
lib('/usr/lib/libSDL3_ttf.so.0.2.2').
lib('/usr/lib/libSM.so.6').
lib('/usr/lib/libSM.so.6.0.1').
lib('/usr/lib/libSPIRV-Tools-diff.so').
lib('/usr/lib/libSPIRV-Tools-link.so').
lib('/usr/lib/libSPIRV-Tools-lint.so').
lib('/usr/lib/libSPIRV-Tools-opt.so').
lib('/usr/lib/libSPIRV-Tools-reduce.so').
lib('/usr/lib/libSPIRV-Tools-shared.so').
lib('/usr/lib/libSPIRV-Tools.so').
lib('/usr/lib/libSvtAv1Enc.so.4').
lib('/usr/lib/libSvtAv1Enc.so.4.1.0').
lib('/usr/lib/libX11-xcb.so.1').
lib('/usr/lib/libX11-xcb.so.1.0.0').
lib('/usr/lib/libX11.so.6').
lib('/usr/lib/libX11.so.6.4.0').
lib('/usr/lib/libXau.so.6').
lib('/usr/lib/libXau.so.6.0.0').
lib('/usr/lib/libXcomposite.so.1').
lib('/usr/lib/libXcomposite.so.1.0.0').
lib('/usr/lib/libXcursor.so.1').
lib('/usr/lib/libXcursor.so.1.0.2').
lib('/usr/lib/libXdamage.so.1').
lib('/usr/lib/libXdamage.so.1.1.0').
lib('/usr/lib/libXdmcp.so.6').
lib('/usr/lib/libXdmcp.so.6.0.0').
lib('/usr/lib/libXext.so.6').
lib('/usr/lib/libXext.so.6.4.0').
lib('/usr/lib/libXfixes.so.3').
lib('/usr/lib/libXfixes.so.3.1.0').
lib('/usr/lib/libXft.so.2').
lib('/usr/lib/libXft.so.2.3.9').
lib('/usr/lib/libXi.so.6').
lib('/usr/lib/libXi.so.6.1.0').
lib('/usr/lib/libXinerama.so.1').
lib('/usr/lib/libXinerama.so.1.0.0').
lib('/usr/lib/libXpm.so.4').
lib('/usr/lib/libXpm.so.4.11.0').
lib('/usr/lib/libXrandr.so.2').
lib('/usr/lib/libXrandr.so.2.2.0').
lib('/usr/lib/libXrender.so.1').
lib('/usr/lib/libXrender.so.1.3.0').
lib('/usr/lib/libXt.so.6').
lib('/usr/lib/libXt.so.6.0.0').
lib('/usr/lib/libXtst.so.6').
lib('/usr/lib/libXtst.so.6.1.0').
lib('/usr/lib/libXxf86vm.so.1').
lib('/usr/lib/libXxf86vm.so.1.0.0').
lib('/usr/lib/libaom.so.3').
lib('/usr/lib/libaom.so.3.14.1').
lib('/usr/lib/libapk.so.3.0.0').
lib('/usr/lib/libasound.so.2').
lib('/usr/lib/libasound.so.2.0.0').
lib('/usr/lib/libatk-1.0.so.0').
lib('/usr/lib/libatk-1.0.so.0.26014.1').
lib('/usr/lib/libatk-bridge-2.0.so.0').
lib('/usr/lib/libatk-bridge-2.0.so.0.0.0').
lib('/usr/lib/libatopology.so.2').
lib('/usr/lib/libatopology.so.2.0.0').
lib('/usr/lib/libatspi.so.0').
lib('/usr/lib/libatspi.so.0.0.1').
lib('/usr/lib/libavahi-client.so.3').
lib('/usr/lib/libavahi-client.so.3.2.9').
lib('/usr/lib/libavahi-common.so.3').
lib('/usr/lib/libavahi-common.so.3.5.4').
lib('/usr/lib/libavcodec.so.62').
lib('/usr/lib/libavcodec.so.62.28.102').
lib('/usr/lib/libavif.so.16').
lib('/usr/lib/libavif.so.16.4.1').
lib('/usr/lib/libavutil.so.60').
lib('/usr/lib/libavutil.so.60.26.102').
lib('/usr/lib/libblkid.so.1').
lib('/usr/lib/libblkid.so.1.1.0').
lib('/usr/lib/libbrotlicommon.so.1').
lib('/usr/lib/libbrotlicommon.so.1.2.0').
lib('/usr/lib/libbrotlidec.so.1').
lib('/usr/lib/libbrotlidec.so.1.2.0').
lib('/usr/lib/libbrotlienc.so.1').
lib('/usr/lib/libbrotlienc.so.1.2.0').
lib('/usr/lib/libbsd.so.0').
lib('/usr/lib/libbsd.so.0.12.2').
lib('/usr/lib/libbz2.so.1').
lib('/usr/lib/libbz2.so.1.0.8').
lib('/usr/lib/libcairo-gobject.so.2').
lib('/usr/lib/libcairo-gobject.so.2.11804.4').
lib('/usr/lib/libcairo-script-interpreter.so.2').
lib('/usr/lib/libcairo-script-interpreter.so.2.11804.4').
lib('/usr/lib/libcairo.so.2').
lib('/usr/lib/libcairo.so.2.11804.4').
lib('/usr/lib/libcap.so.2').
lib('/usr/lib/libcap.so.2.78').
lib('/usr/lib/libcdt.so.5').
lib('/usr/lib/libcdt.so.5.0.0').
lib('/usr/lib/libcgraph.so.6').
lib('/usr/lib/libcgraph.so.6.0.0').
lib('/usr/lib/libcom_err.so.2').
lib('/usr/lib/libcom_err.so.2.1').
lib('/usr/lib/libcrypto.so.3').
lib('/usr/lib/libcups.so.2').
lib('/usr/lib/libcupsimage.so.2').
lib('/usr/lib/libdav1d.so.7').
lib('/usr/lib/libdav1d.so.7.0.0').
lib('/usr/lib/libdbus-1.so.3').
lib('/usr/lib/libdbus-1.so.3.38.3').
lib('/usr/lib/libdisplay-info.so.0.3.0').
lib('/usr/lib/libdisplay-info.so.3').
lib('/usr/lib/libdrm.so.2').
lib('/usr/lib/libdrm.so.2.134.0').
lib('/usr/lib/libdrm_amdgpu.so.1').
lib('/usr/lib/libdrm_amdgpu.so.1.134.0').
lib('/usr/lib/libdrm_etnaviv.so.1').
lib('/usr/lib/libdrm_etnaviv.so.1.134.0').
lib('/usr/lib/libdrm_exynos.so.1').
lib('/usr/lib/libdrm_exynos.so.1.134.0').
lib('/usr/lib/libdrm_freedreno.so.1').
lib('/usr/lib/libdrm_freedreno.so.1.134.0').
lib('/usr/lib/libdrm_intel.so.1').
lib('/usr/lib/libdrm_intel.so.1.134.0').
lib('/usr/lib/libdrm_nouveau.so.2').
lib('/usr/lib/libdrm_nouveau.so.2.134.0').
lib('/usr/lib/libdrm_omap.so.1').
lib('/usr/lib/libdrm_omap.so.1.134.0').
lib('/usr/lib/libdrm_radeon.so.1').
lib('/usr/lib/libdrm_radeon.so.1.134.0').
lib('/usr/lib/libdrm_tegra.so.0').
lib('/usr/lib/libdrm_tegra.so.0.134.0').
lib('/usr/lib/libeconf.so.0').
lib('/usr/lib/libeconf.so.0.8.3').
lib('/usr/lib/libedit.so.0').
lib('/usr/lib/libedit.so.0.0.77').
lib('/usr/lib/libelf-0.195.so').
lib('/usr/lib/libelf.so.1').
lib('/usr/lib/libelogind.so.0').
lib('/usr/lib/libelogind.so.0.38.0').
lib('/usr/lib/libepoxy.so.0').
lib('/usr/lib/libepoxy.so.0.0.0').
lib('/usr/lib/libevdev.so.2').
lib('/usr/lib/libevdev.so.2.3.0').
lib('/usr/lib/libevent-2.1.so.7').
lib('/usr/lib/libevent-2.1.so.7.0.2').
lib('/usr/lib/libevent_core-2.1.so.7').
lib('/usr/lib/libevent_core-2.1.so.7.0.2').
lib('/usr/lib/libevent_extra-2.1.so.7').
lib('/usr/lib/libevent_extra-2.1.so.7.0.2').
lib('/usr/lib/libevent_openssl-2.1.so.7').
lib('/usr/lib/libevent_openssl-2.1.so.7.0.2').
lib('/usr/lib/libevent_pthreads-2.1.so.7').
lib('/usr/lib/libevent_pthreads-2.1.so.7.0.2').
lib('/usr/lib/libexpat.so.1').
lib('/usr/lib/libexpat.so.1.12.2').
lib('/usr/lib/libfdk-aac.so.2').
lib('/usr/lib/libfdk-aac.so.2.0.2').
lib('/usr/lib/libffi.so.8').
lib('/usr/lib/libffi.so.8.2.0').
lib('/usr/lib/libfftw3.so.3').
lib('/usr/lib/libfftw3.so.3.7.11').
lib('/usr/lib/libfftw3_threads.so.3').
lib('/usr/lib/libfftw3_threads.so.3.7.11').
lib('/usr/lib/libfftw3f.so.3').
lib('/usr/lib/libfftw3f.so.3.7.11').
lib('/usr/lib/libfftw3f_threads.so.3').
lib('/usr/lib/libfftw3f_threads.so.3.7.11').
lib('/usr/lib/libfftw3l.so.3').
lib('/usr/lib/libfftw3l.so.3.7.11').
lib('/usr/lib/libfftw3l_threads.so.3').
lib('/usr/lib/libfftw3l_threads.so.3.7.11').
lib('/usr/lib/libfontconfig.so.1').
lib('/usr/lib/libfontconfig.so.1.16.1').
lib('/usr/lib/libfontenc.so.1').
lib('/usr/lib/libfontenc.so.1.0.0').
lib('/usr/lib/libfreebl3.so').
lib('/usr/lib/libfreebl3.so.124').
lib('/usr/lib/libfreeblpriv3.so').
lib('/usr/lib/libfreeblpriv3.so.124').
lib('/usr/lib/libfreerdp-client3.so.3').
lib('/usr/lib/libfreerdp-client3.so.3.29.0').
lib('/usr/lib/libfreerdp-server-proxy3.so.3').
lib('/usr/lib/libfreerdp-server-proxy3.so.3.29.0').
lib('/usr/lib/libfreerdp-server3.so.3').
lib('/usr/lib/libfreerdp-server3.so.3.29.0').
lib('/usr/lib/libfreerdp-shadow-subsystem3.so.3').
lib('/usr/lib/libfreerdp-shadow-subsystem3.so.3.29.0').
lib('/usr/lib/libfreerdp-shadow3.so.3').
lib('/usr/lib/libfreerdp-shadow3.so.3.29.0').
lib('/usr/lib/libfreerdp3.so.3').
lib('/usr/lib/libfreerdp3.so.3.29.0').
lib('/usr/lib/libfreetype.so.6').
lib('/usr/lib/libfreetype.so.6.20.6').
lib('/usr/lib/libfribidi.so.0').
lib('/usr/lib/libfribidi.so.0.4.0').
lib('/usr/lib/libfuse3.so.3.18.2').
lib('/usr/lib/libfuse3.so.4').
lib('/usr/lib/libgailutil-3.so.0').
lib('/usr/lib/libgailutil-3.so.0.0.0').
lib('/usr/lib/libgallium-26.1.1.so').
lib('/usr/lib/libgbm.so.1').
lib('/usr/lib/libgbm.so.1.0.0').
lib('/usr/lib/libgcc_s.so.1').
lib('/usr/lib/libgd.so.3').
lib('/usr/lib/libgd.so.3.0.11').
lib('/usr/lib/libgdk-3.so.0').
lib('/usr/lib/libgdk-3.so.0.2420.32').
lib('/usr/lib/libgdk_pixbuf-2.0.so.0').
lib('/usr/lib/libgdk_pixbuf-2.0.so.0.4400.7').
lib('/usr/lib/libgio-2.0.so.0').
lib('/usr/lib/libgio-2.0.so.0.8800.1').
lib('/usr/lib/libgirepository-1.0.so.1').
lib('/usr/lib/libgirepository-1.0.so.1.0.0').
lib('/usr/lib/libgirepository-2.0.so.0').
lib('/usr/lib/libgirepository-2.0.so.0.8800.1').
lib('/usr/lib/libglib-2.0.so.0').
lib('/usr/lib/libglib-2.0.so.0.8800.1').
lib('/usr/lib/libglycin-2.so.0').
lib('/usr/lib/libgmodule-2.0.so.0').
lib('/usr/lib/libgmodule-2.0.so.0.8800.1').
lib('/usr/lib/libgmp.so.10').
lib('/usr/lib/libgmp.so.10.5.0').
lib('/usr/lib/libgnutls.so.30').
lib('/usr/lib/libgnutls.so.30.42.0').
lib('/usr/lib/libgobject-2.0.so.0').
lib('/usr/lib/libgobject-2.0.so.0.8800.1').
lib('/usr/lib/libgomp.so.1').
lib('/usr/lib/libgomp.so.1.0.0').
lib('/usr/lib/libgraphite2.so.3').
lib('/usr/lib/libgraphite2.so.3.2.1').
lib('/usr/lib/libgsm.so.1').
lib('/usr/lib/libgsm.so.1.0.12').
lib('/usr/lib/libgssapi_krb5.so.2').
lib('/usr/lib/libgssapi_krb5.so.2.2').
lib('/usr/lib/libgssrpc.so.4').
lib('/usr/lib/libgssrpc.so.4.2').
lib('/usr/lib/libgthread-2.0.so.0').
lib('/usr/lib/libgthread-2.0.so.0.8800.1').
lib('/usr/lib/libgtk-3.so.0').
lib('/usr/lib/libgtk-3.so.0.2420.32').
lib('/usr/lib/libgvc.so.6').
lib('/usr/lib/libgvc.so.6.0.0').
lib('/usr/lib/libgvpr.so.2').
lib('/usr/lib/libgvpr.so.2.0.0').
lib('/usr/lib/libharfbuzz-raster.so.0').
lib('/usr/lib/libharfbuzz-raster.so.0.61321.0').
lib('/usr/lib/libharfbuzz-vector.so.0').
lib('/usr/lib/libharfbuzz-vector.so.0.61321.0').
lib('/usr/lib/libharfbuzz.so.0').
lib('/usr/lib/libharfbuzz.so.0.61321.0').
lib('/usr/lib/libhogweed.so.6').
lib('/usr/lib/libhogweed.so.6.11').
lib('/usr/lib/libhwy.so.1').
lib('/usr/lib/libhwy.so.1.3.0').
lib('/usr/lib/libicudata.so.78').
lib('/usr/lib/libicudata.so.78.1').
lib('/usr/lib/libicui18n.so.78').
lib('/usr/lib/libicui18n.so.78.1').
lib('/usr/lib/libicuio.so.78').
lib('/usr/lib/libicuio.so.78.1').
lib('/usr/lib/libicuuc.so.78').
lib('/usr/lib/libicuuc.so.78.1').
lib('/usr/lib/libidn2.so.0').
lib('/usr/lib/libidn2.so.0.4.0').
lib('/usr/lib/libinput.so.10').
lib('/usr/lib/libinput.so.10.13.0').
lib('/usr/lib/libintl.so.8').
lib('/usr/lib/libintl.so.8.4.6').
lib('/usr/lib/libjpeg.so.8').
lib('/usr/lib/libjpeg.so.8.3.2').
lib('/usr/lib/libjson-c.so.5').
lib('/usr/lib/libjson-c.so.5.4.0').
lib('/usr/lib/libjxl.so.0.11').
lib('/usr/lib/libjxl.so.0.11.2').
lib('/usr/lib/libjxl_cms.so.0.11').
lib('/usr/lib/libjxl_cms.so.0.11.2').
lib('/usr/lib/libjxl_threads.so.0.11').
lib('/usr/lib/libjxl_threads.so.0.11.2').
lib('/usr/lib/libk5crypto.so.3').
lib('/usr/lib/libk5crypto.so.3.1').
lib('/usr/lib/libkadm5clnt_mit.so.12').
lib('/usr/lib/libkadm5clnt_mit.so.12.0').
lib('/usr/lib/libkadm5srv_mit.so.12').
lib('/usr/lib/libkadm5srv_mit.so.12.0').
lib('/usr/lib/libkdb5.so.10').
lib('/usr/lib/libkdb5.so.10.0').
lib('/usr/lib/libkeyutils.so.1').
lib('/usr/lib/libkeyutils.so.1.10').
lib('/usr/lib/libkrad.so.0').
lib('/usr/lib/libkrad.so.0.0').
lib('/usr/lib/libkrb5.so.3').
lib('/usr/lib/libkrb5.so.3.3').
lib('/usr/lib/libkrb5support.so.0').
lib('/usr/lib/libkrb5support.so.0.1').
lib('/usr/lib/liblcms2.so.2').
lib('/usr/lib/liblcms2.so.2.0.19').
lib('/usr/lib/libliftoff.so.0').
lib('/usr/lib/libliftoff.so.0.5.0').
lib('/usr/lib/liblzma.so.5').
lib('/usr/lib/liblzma.so.5.8.3').
lib('/usr/lib/libmd.so.0').
lib('/usr/lib/libmd.so.0.2.0').
lib('/usr/lib/libmount.so.1').
lib('/usr/lib/libmount.so.1.1.0').
lib('/usr/lib/libmp3lame.so.0').
lib('/usr/lib/libmp3lame.so.0.0.0').
lib('/usr/lib/libmtdev.so.1').
lib('/usr/lib/libmtdev.so.1.0.0').
lib('/usr/lib/libncursesw.so.6').
lib('/usr/lib/libncursesw.so.6.6').
lib('/usr/lib/libnettle.so.8').
lib('/usr/lib/libnettle.so.8.11').
lib('/usr/lib/libnspr4.so').
lib('/usr/lib/libnss3.so').
lib('/usr/lib/libnss3.so.124').
lib('/usr/lib/libnssckbi-testlib.so').
lib('/usr/lib/libnssckbi-testlib.so.124').
lib('/usr/lib/libnssckbi.so').
lib('/usr/lib/libnssckbi.so.124').
lib('/usr/lib/libnsssysinit.so').
lib('/usr/lib/libnsssysinit.so.124').
lib('/usr/lib/libnssutil3.so').
lib('/usr/lib/libnssutil3.so.124').
lib('/usr/lib/libnuma.so.1').
lib('/usr/lib/libnuma.so.1.0.0').
lib('/usr/lib/libogg.so.0').
lib('/usr/lib/libogg.so.0.8.6').
lib('/usr/lib/libopenh264.so.2.6.0').
lib('/usr/lib/libopenh264.so.8').
lib('/usr/lib/libopus.so.0').
lib('/usr/lib/libopus.so.0.11.1').
lib('/usr/lib/libp11-kit.so.0').
lib('/usr/lib/libp11-kit.so.0.4.8').
lib('/usr/lib/libpango-1.0.so.0').
lib('/usr/lib/libpango-1.0.so.0.5701.0').
lib('/usr/lib/libpangocairo-1.0.so.0').
lib('/usr/lib/libpangocairo-1.0.so.0.5701.0').
lib('/usr/lib/libpangoft2-1.0.so.0').
lib('/usr/lib/libpangoft2-1.0.so.0.5701.0').
lib('/usr/lib/libpangoxft-1.0.so.0').
lib('/usr/lib/libpangoxft-1.0.so.0.5701.0').
lib('/usr/lib/libpathplan.so.4').
lib('/usr/lib/libpathplan.so.4.0.0').
lib('/usr/lib/libpci.so.3').
lib('/usr/lib/libpci.so.3.15.0').
lib('/usr/lib/libpciaccess.so.0').
lib('/usr/lib/libpciaccess.so.0.11.1').
lib('/usr/lib/libpcre2-8.so.0').
lib('/usr/lib/libpcre2-8.so.0.15.0').
lib('/usr/lib/libpcre2-posix.so.3').
lib('/usr/lib/libpcre2-posix.so.3.0.7').
lib('/usr/lib/libpixman-1.so.0').
lib('/usr/lib/libpixman-1.so.0.46.4').
lib('/usr/lib/libpkgconf.so.7').
lib('/usr/lib/libpkgconf.so.7.0.0').
lib('/usr/lib/libplc4.so').
lib('/usr/lib/libplds4.so').
lib('/usr/lib/libpng16.so.16').
lib('/usr/lib/libpng16.so.16.58.0').
lib('/usr/lib/libpsx.so.2').
lib('/usr/lib/libpsx.so.2.78').
lib('/usr/lib/librav1e.so.0.8').
lib('/usr/lib/librav1e.so.0.8.1').
lib('/usr/lib/librsvg-2.so.2').
lib('/usr/lib/librsvg-2.so.2.62.3').
lib('/usr/lib/libscudo.so').
lib('/usr/lib/libseat.so.1').
lib('/usr/lib/libseccomp.so.2').
lib('/usr/lib/libseccomp.so.2.6.0').
lib('/usr/lib/libsharpyuv.so.0').
lib('/usr/lib/libsharpyuv.so.0.1.2').
lib('/usr/lib/libsmime3.so').
lib('/usr/lib/libsmime3.so.124').
lib('/usr/lib/libsoftokn3.so').
lib('/usr/lib/libsoftokn3.so.124').
lib('/usr/lib/libsoxr-lsr.so.0').
lib('/usr/lib/libsoxr-lsr.so.0.1.9').
lib('/usr/lib/libsoxr.so.0').
lib('/usr/lib/libsoxr.so.0.1.2').
lib('/usr/lib/libsqlite3.so.0').
lib('/usr/lib/libsqlite3.so.3.53.2').
lib('/usr/lib/libssl.so.3').
lib('/usr/lib/libssl3.so').
lib('/usr/lib/libssl3.so.124').
lib('/usr/lib/libstdc++.so.6').
lib('/usr/lib/libstdc++.so.6.0.34').
lib('/usr/lib/libswresample.so.6').
lib('/usr/lib/libswresample.so.6.3.102').
lib('/usr/lib/libtasn1.so.6').
lib('/usr/lib/libtasn1.so.6.6.5').
lib('/usr/lib/libtheora.so.1').
lib('/usr/lib/libtheora.so.1.4.1').
lib('/usr/lib/libtheoradec.so.2').
lib('/usr/lib/libtheoradec.so.2.1.1').
lib('/usr/lib/libtheoraenc.so.2').
lib('/usr/lib/libtheoraenc.so.2.2.1').
lib('/usr/lib/libtiff.so.6').
lib('/usr/lib/libtiff.so.6.2.0').
lib('/usr/lib/libudev.so.1').
lib('/usr/lib/libudev.so.1.6.3').
lib('/usr/lib/libunistring.so.5').
lib('/usr/lib/libunistring.so.5.2.1').
lib('/usr/lib/libusb-1.0.so.0').
lib('/usr/lib/libusb-1.0.so.0.6.0').
lib('/usr/lib/libuuid.so.1').
lib('/usr/lib/libuuid.so.1.3.0').
lib('/usr/lib/libva-drm.so.2').
lib('/usr/lib/libva-drm.so.2.2300.0').
lib('/usr/lib/libva-wayland.so.2').
lib('/usr/lib/libva-wayland.so.2.2300.0').
lib('/usr/lib/libva-x11.so.2').
lib('/usr/lib/libva-x11.so.2.2300.0').
lib('/usr/lib/libva.so.2').
lib('/usr/lib/libva.so.2.2300.0').
lib('/usr/lib/libvdpau.so.1').
lib('/usr/lib/libvdpau.so.1.0.0').
lib('/usr/lib/libverto.so.1').
lib('/usr/lib/libverto.so.1.0.0').
lib('/usr/lib/libvorbis.so.0').
lib('/usr/lib/libvorbis.so.0.4.9').
lib('/usr/lib/libvorbisenc.so.2').
lib('/usr/lib/libvorbisenc.so.2.0.12').
lib('/usr/lib/libvorbisfile.so.3').
lib('/usr/lib/libvorbisfile.so.3.3.8').
lib('/usr/lib/libvpx.so.11').
lib('/usr/lib/libvpx.so.11.0').
lib('/usr/lib/libvpx.so.11.0.1').
lib('/usr/lib/libvulkan.so.1').
lib('/usr/lib/libvulkan.so.1.4.347').
lib('/usr/lib/libwayland-client.so.0').
lib('/usr/lib/libwayland-client.so.0.25.0').
lib('/usr/lib/libwayland-cursor.so.0').
lib('/usr/lib/libwayland-cursor.so.0.25.0').
lib('/usr/lib/libwayland-egl.so.1').
lib('/usr/lib/libwayland-egl.so.1.25.0').
lib('/usr/lib/libwayland-server.so.0').
lib('/usr/lib/libwayland-server.so.0.25.0').
lib('/usr/lib/libwebp.so.7').
lib('/usr/lib/libwebp.so.7.2.0').
lib('/usr/lib/libwebpdemux.so.2').
lib('/usr/lib/libwebpdemux.so.2.0.17').
lib('/usr/lib/libwebpmux.so.3').
lib('/usr/lib/libwebpmux.so.3.1.2').
lib('/usr/lib/libwinpr-tools3.so.3').
lib('/usr/lib/libwinpr-tools3.so.3.29.0').
lib('/usr/lib/libwinpr3.so.3').
lib('/usr/lib/libwinpr3.so.3.29.0').
lib('/usr/lib/libwlroots-0.19.so').
lib('/usr/lib/libx264.so.164').
lib('/usr/lib/libx265.so.215').
lib('/usr/lib/libxcb-composite.so.0').
lib('/usr/lib/libxcb-composite.so.0.0.0').
lib('/usr/lib/libxcb-damage.so.0').
lib('/usr/lib/libxcb-damage.so.0.0.0').
lib('/usr/lib/libxcb-dbe.so.0').
lib('/usr/lib/libxcb-dbe.so.0.0.0').
lib('/usr/lib/libxcb-dpms.so.0').
lib('/usr/lib/libxcb-dpms.so.0.0.0').
lib('/usr/lib/libxcb-dri2.so.0').
lib('/usr/lib/libxcb-dri2.so.0.0.0').
lib('/usr/lib/libxcb-dri3.so.0').
lib('/usr/lib/libxcb-dri3.so.0.1.0').
lib('/usr/lib/libxcb-ewmh.so.2').
lib('/usr/lib/libxcb-ewmh.so.2.0.0').
lib('/usr/lib/libxcb-glx.so.0').
lib('/usr/lib/libxcb-glx.so.0.0.0').
lib('/usr/lib/libxcb-icccm.so.4').
lib('/usr/lib/libxcb-icccm.so.4.0.0').
lib('/usr/lib/libxcb-present.so.0').
lib('/usr/lib/libxcb-present.so.0.0.0').
lib('/usr/lib/libxcb-randr.so.0').
lib('/usr/lib/libxcb-randr.so.0.1.0').
lib('/usr/lib/libxcb-record.so.0').
lib('/usr/lib/libxcb-record.so.0.0.0').
lib('/usr/lib/libxcb-render-util.so.0').
lib('/usr/lib/libxcb-render-util.so.0.0.0').
lib('/usr/lib/libxcb-render.so.0').
lib('/usr/lib/libxcb-render.so.0.0.0').
lib('/usr/lib/libxcb-res.so.0').
lib('/usr/lib/libxcb-res.so.0.0.0').
lib('/usr/lib/libxcb-screensaver.so.0').
lib('/usr/lib/libxcb-screensaver.so.0.0.0').
lib('/usr/lib/libxcb-shape.so.0').
lib('/usr/lib/libxcb-shape.so.0.0.0').
lib('/usr/lib/libxcb-shm.so.0').
lib('/usr/lib/libxcb-shm.so.0.0.0').
lib('/usr/lib/libxcb-sync.so.1').
lib('/usr/lib/libxcb-sync.so.1.0.0').
lib('/usr/lib/libxcb-xf86dri.so.0').
lib('/usr/lib/libxcb-xf86dri.so.0.0.0').
lib('/usr/lib/libxcb-xfixes.so.0').
lib('/usr/lib/libxcb-xfixes.so.0.0.0').
lib('/usr/lib/libxcb-xinerama.so.0').
lib('/usr/lib/libxcb-xinerama.so.0.0.0').
lib('/usr/lib/libxcb-xinput.so.0').
lib('/usr/lib/libxcb-xinput.so.0.1.0').
lib('/usr/lib/libxcb-xkb.so.1').
lib('/usr/lib/libxcb-xkb.so.1.0.0').
lib('/usr/lib/libxcb-xtest.so.0').
lib('/usr/lib/libxcb-xtest.so.0.0.0').
lib('/usr/lib/libxcb-xv.so.0').
lib('/usr/lib/libxcb-xv.so.0.0.0').
lib('/usr/lib/libxcb-xvmc.so.0').
lib('/usr/lib/libxcb-xvmc.so.0.0.0').
lib('/usr/lib/libxcb.so.1').
lib('/usr/lib/libxcb.so.1.1.0').
lib('/usr/lib/libxdot.so.4').
lib('/usr/lib/libxdot.so.4.0.0').
lib('/usr/lib/libxkbcommon.so.0').
lib('/usr/lib/libxkbcommon.so.0.13.1').
lib('/usr/lib/libxkbfile.so.1').
lib('/usr/lib/libxkbfile.so.1.0.2').
lib('/usr/lib/libxkbregistry.so.0').
lib('/usr/lib/libxkbregistry.so.0.13.1').
lib('/usr/lib/libxml2.so.2').
lib('/usr/lib/libxml2.so.2.13.9').
lib('/usr/lib/libxshmfence.so.1').
lib('/usr/lib/libxshmfence.so.1.0.0').
lib('/usr/lib/libxvidcore.so.4').
lib('/usr/lib/libxvidcore.so.4.3').
lib('/usr/lib/libyuv.so').
lib('/usr/lib/libz.so.1').
lib('/usr/lib/libz.so.1.3.2').
lib('/usr/lib/libzstd.so.1').
lib('/usr/lib/libzstd.so.1.5.7').
lib('/usr/lib/llvm22/lib/libLLVM-22.so').
lib('/usr/lib/llvm22/lib/libLLVM.so.22.1').
lib('/usr/lib/ossl-modules/legacy.so').
lib('/usr/lib/vdpau/libvdpau_trace.so').
lib('/usr/lib/vdpau/libvdpau_trace.so.1').
lib('/usr/lib/vdpau/libvdpau_trace.so.1.0.0').